### ISSUE TITLE
Add New feature (Font Family)

### ISSUE THREAD

**Issue by neeravnadla** [neeravnadla/paper#1]
--- New Feature ----
Change Font Family when tapping on the "A" labeled button in the bottom row.

<img width="360" alt="Untitled" src="https://user-images.githubusercontent.com/19428280/148093091-a2f1b3a0-812e-4945-acc7-f81822be1849.png">

Also 
- Multiple Font Style. 
- On each tap Font Family Change (no dropdown menu)

**Comment by aliraza944** [comment]
Hi, I have resolved the issue in the pull request.  Kindly check and verify.

**Comment by neeravnadla** [comment]
@aliraza944 hey thanks but you are supposed to change FONT FAMILY, not Font Style.

**Comment by aliraza944** [comment]
I have changed the font family of course. It's just an error on the commit message.
